# Generated by Django 2.2.6 on 2019-10-26 13:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='key',
        ),
        migrations.AddField(
            model_name='request',
            name='enc_field',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='None', max_length=400), size=None), default=[], size=None),
        ),
    ]
