# Generated by Django 2.2.6 on 2019-10-26 13:22

import EMS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0003_auto_20191026_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='teacher_id',
            field=models.CharField(blank=True, default=EMS.models.teacherID, max_length=20),
        ),
    ]
