# Generated by Django 2.2.6 on 2019-10-30 07:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0007_auto_20191026_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='enc_field',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BinaryField(default='None', max_length=2000), size=None), default=list, size=None),
        ),
    ]
