# Generated by Django 2.2.6 on 2019-11-03 06:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0010_auto_20191103_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='enc_field',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BinaryField(default='None', max_length=500), size=None),
        ),
    ]
