# Generated by Django 2.2.6 on 2019-11-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0011_auto_20191103_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='enc_field',
        ),
    ]
