# Generated by Django 2.2.6 on 2019-11-03 07:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0012_remove_request_enc_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='enc_field',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BinaryField(default=None, max_length=500), default=list, size=None),
        ),
    ]
