# Generated by Django 2.2.6 on 2019-11-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0014_remove_request_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalPapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_code', models.CharField(default='None', max_length=7)),
                ('course', models.CharField(default='None', max_length=4)),
                ('semester', models.CharField(default='None', max_length=4)),
                ('branch', models.CharField(default='None', max_length=40)),
                ('subject', models.CharField(default='None', max_length=30)),
                ('paper', models.FileField(default=None, upload_to='')),
            ],
        ),
    ]
