# Generated by Django 2.2.6 on 2025-02-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0015_finalpapers'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalpapers',
            name='blockchain_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
