# Generated by Django 4.2.19 on 2025-03-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0017_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalpapers',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
