# Generated by Django 4.2.19 on 2025-03-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0018_finalpapers_tx_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default='Pending', max_length=25),
        ),
    ]
