# Generated by Django 4.2.19 on 2025-03-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0019_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='encrypted_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
