# Generated by Django 4.2.19 on 2025-03-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0020_request_encrypted_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='deadline',
        ),
        migrations.AddField(
            model_name='request',
            name='exam_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='paper_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
