# Generated by Django 4.2.19 on 2025-03-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0021_remove_request_deadline_request_exam_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalpapers',
            name='download_tx_hash',
            field=models.CharField(blank=True, help_text='Blockchain transaction hash for the download event.', max_length=100, null=True),
        ),
    ]
