# Generated by Django 4.2.19 on 2025-03-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0022_finalpapers_download_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalpapers',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
