# Generated by Django 4.2.19 on 2025-03-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0023_finalpapers_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalpapers',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
