# Generated by Django 4.2.19 on 2025-03-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0024_finalpapers_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalpapers',
            name='contract_paper_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
